---

- name: tech talk demo playbook to create a vm from a template
  hosts: localhost
  gather_facts: false
  roles:
  - create_vm_from_template

- name: register new vm to satellite
  hosts: new_vms
  roles:
  - register_satellite
